exec 'Snippet mw class MainWindow(QtGui.QMainWindow):<ESC>odef __init__(self):<ESC>oQtGui.QMainWindow.__init__(self)<ESC>'
exec 'Snippet app app = QtGui.QApplication(sys.argv)<ESC>omain = <{MW}><ESC>omain.show()<ESC>osys.exit(app.exec_())'
exec 'Snippet swt self.setWindowTitle(<{}>)'
exec 'Snippet srs self.resize(<{250}>, <{150}>)'
exec 'Snippet sban #!/usr/bin/env python'
